from . import db

class Race(db.Model):
    __tablename__ = 'race'
    id = db.Column(db.Integer, nullable=False, unique=True, primary_key=True)
    name = db.Column(db.String(), nullable=False)
    gender = db.Column(db.String(), nullable=False)
    strength = db.Column(db.Integer(), nullable=False, default=40)
    endurance = db.Column(db.Integer(), nullable=False, default=40)
    speed = db.Column(db.Integer(), nullable=False, default=40)
    agility = db.Column(db.Integer(), nullable=False, default=40)
    personality = db.Column(db.Integer(), nullable=False, default=40)
    intelligence = db.Column(db.Integer(), nullable=False, default=40)
    willpower = db.Column(db.Integer(), nullable=False, default=40)
    luck = db.Column(db.Integer(), nullable=False, default=50)
    blade = db.Column(db.Integer(), nullable=False, default=0)
    blunt = db.Column(db.Integer(), nullable=False, default=0)
    hand_to_hand = db.Column(db.Integer(), nullable=False, default=0)
    armorer = db.Column(db.Integer(), nullable=False, default=0)
    block = db.Column(db.Integer(), nullable=False, default=0)
    heavy_armor = db.Column(db.Integer(), nullable=False, default=0)
    athletics = db.Column(db.Integer(), nullable=False, default=0)
    acrobatics = db.Column(db.Integer(), nullable=False, default=0)
    light_armor = db.Column(db.Integer(), nullable=False, default=0)
    security = db.Column(db.Integer(), nullable=False, default=0)
    sneak = db.Column(db.Integer(), nullable=False, default=0)
    marksman = db.Column(db.Integer(), nullable=False, default=0)
    mercantile = db.Column(db.Integer(), nullable=False, default=0)
    speechcraft = db.Column(db.Integer(), nullable=False, default=0)
    illusion = db.Column(db.Integer(), nullable=False, default=0)
    alchemy = db.Column(db.Integer(), nullable=False, default=0)
    conjuration = db.Column(db.Integer(), nullable=False, default=0)
    mysticism = db.Column(db.Integer(), nullable=False, default=0)
    alteration = db.Column(db.Integer(), nullable=False, default=0)
    destruction = db.Column(db.Integer(), nullable=False, default=0)
    restoration = db.Column(db.Integer(), nullable=False, default=0)
    magicka = db.Column(db.Integer(), nullable=False, default=0)
    fire_res = db.Column(db.Integer(), nullable=False, default=0)
    cold_res = db.Column(db.Integer(), nullable=False, default=0)
    shock_res = db.Column(db.Integer(), nullable=False, default=0)
    poison_res = db.Column(db.Integer(), nullable=False, default=0)
    magic_res = db.Column(db.Integer(), nullable=False, default=0)
    disease_res = db.Column(db.Integer(), nullable=False, default=0)
    
class BirthSign(db.Model):
    __tablename__ = 'birthsign'
    id = db.Column(db.Integer, nullable=False, unique=True, primary_key=True)
    name = db.Column(db.String(), unique=True, nullable=False)
    strength = db.Column(db.Integer(), nullable=False, default=0)
    endurance = db.Column(db.Integer(), nullable=False, default=0)
    speed = db.Column(db.Integer(), nullable=False, default=0)
    agility = db.Column(db.Integer(), nullable=False, default=0)
    personality = db.Column(db.Integer(), nullable=False, default=0)
    willpower = db.Column(db.Integer(), nullable=False, default=0)
    intelligence = db.Column(db.Integer(), nullable=False, default=0)
    luck = db.Column(db.Integer(), nullable=False, default=0)

class Class(db.Model):
    __tablename__ = 'class'
    id = db.Column(db.Integer, nullable=False, unique=True, primary_key=True)
    name = db.Column(db.String(), unique=True, nullable=False)
    strength = db.Column(db.Integer(), nullable=False, default=0)
    endurance = db.Column(db.Integer(), nullable=False, default=0)
    speed = db.Column(db.Integer(), nullable=False, default=0)
    agility = db.Column(db.Integer(), nullable=False, default=0)
    personality = db.Column(db.Integer(), nullable=False, default=0)
    intelligence = db.Column(db.Integer(), nullable=False, default=0)
    willpower = db.Column(db.Integer(), nullable=False, default=0)
    blade = db.Column(db.Integer(), nullable=False, default=0)
    blunt = db.Column(db.Integer(), nullable=False, default=0)
    hand_to_hand = db.Column(db.Integer(), nullable=False, default=0)
    armorer = db.Column(db.Integer(), nullable=False, default=0)
    block = db.Column(db.Integer(), nullable=False, default=0)
    heavy_armor = db.Column(db.Integer(), nullable=False, default=0)
    athletics = db.Column(db.Integer(), nullable=False, default=0)
    acrobatics = db.Column(db.Integer(), nullable=False, default=0)
    light_armor = db.Column(db.Integer(), nullable=False, default=0)
    security = db.Column(db.Integer(), nullable=False, default=0)
    sneak = db.Column(db.Integer(), nullable=False, default=0)
    marksman = db.Column(db.Integer(), nullable=False, default=0)
    mercantile = db.Column(db.Integer(), nullable=False, default=0)
    speechcraft = db.Column(db.Integer(), nullable=False, default=0)
    illusion = db.Column(db.Integer(), nullable=False, default=0)
    alchemy = db.Column(db.Integer(), nullable=False, default=0)
    conjuration = db.Column(db.Integer(), nullable=False, default=0)
    mysticism = db.Column(db.Integer(), nullable=False, default=0)
    alteration = db.Column(db.Integer(), nullable=False, default=0)
    destruction = db.Column(db.Integer(), nullable=False, default=0)
    restoration = db.Column(db.Integer(), nullable=False, default=0)
    
class Item(db.Model):
    __tablename__= 'item'
    id = db.Column(db.Integer, nullable=False, unique=True, primary_key=True)
    name = db.Column(db.String(), unique=True, nullable=False)
    skill = db.Column(db.String(), default=None)
    damage = db.Column(db.Integer(), nullable=False, default=0)
    wear = db.Column(db.String(), nullable=False)
    rating = db.Column(db.Integer(), nullable=False, default=0)
    strength = db.Column(db.Integer(), nullable=False, default=0)
    endurance = db.Column(db.Integer(), nullable=False, default=0)
    agility = db.Column(db.Integer(), nullable=False, default=0)
    speed = db.Column(db.Integer(), nullable=False, default=0)
    willpower = db.Column(db.Integer(), nullable=False, default=0)
    intelligence = db.Column(db.Integer(), nullable=False, default=0)
    personality = db.Column(db.Integer(), nullable=False, default=0)
    luck = db.Column(db.Integer(), nullable=False, default=0)
    blade = db.Column(db.Integer(), nullable=False, default=0)
    blunt = db.Column(db.Integer(), nullable=False, default=0)
    hand_to_hand = db.Column(db.Integer(), nullable=False, default=0)
    armorer = db.Column(db.Integer(), nullable=False, default=0)
    block = db.Column(db.Integer(), nullable=False, default=0)
    heavy_armor = db.Column(db.Integer(), nullable=False, default=0)
    athletics = db.Column(db.Integer(), nullable=False, default=0)
    acrobatics = db.Column(db.Integer(), nullable=False, default=0)
    light_armor = db.Column(db.Integer(), nullable=False, default=0)
    security = db.Column(db.Integer(), nullable=False, default=0)
    sneak = db.Column(db.Integer(), nullable=False, default=0)
    marksman = db.Column(db.Integer(), nullable=False, default=0)
    mercantile = db.Column(db.Integer(), nullable=False, default=0)
    speechcraft = db.Column(db.Integer(), nullable=False, default=0)
    illusion = db.Column(db.Integer(), nullable=False, default=0)
    alchemy = db.Column(db.Integer(), nullable=False, default=0)
    conjuration = db.Column(db.Integer(), nullable=False, default=0)
    mysticism = db.Column(db.Integer(), nullable=False, default=0)
    alteration = db.Column(db.Integer(), nullable=False, default=0)
    destruction = db.Column(db.Integer(), nullable=False, default=0)
    restoration = db.Column(db.Integer(), nullable=False, default=0)
    fire_res = db.Column(db.Integer(), nullable=False, default=0)
    cold_res = db.Column(db.Integer(), nullable=False, default=0)
    shock_res = db.Column(db.Integer(), nullable=False, default=0)
    magic_res = db.Column(db.Integer(), nullable=False, default=0)
    poison_res = db.Column(db.Integer(), nullable=False, default=0)
    disease_res = db.Column(db.Integer(), nullable=False, default=0)
    paralysis_res = db.Column(db.Integer(), nullable=False, default=0)
    normal_weapon_res = db.Column(db.Integer(), nullable=False, default=0)
    fire_weak = db.Column(db.Integer(), nullable=False, default=0)
    cold_weak = db.Column(db.Integer(), nullable=False, default=0)
    shock_weak = db.Column(db.Integer(), nullable=False, default=0)
    poison_weak = db.Column(db.Integer(), nullable=False, default=0)
    reflect_dmg = db.Column(db.Integer(), nullable=False, default=0)
    reflect_spell = db.Column(db.Integer(), nullable=False, default=0)
    fire_dmg = db.Column(db.Integer(), nullable=False, default=0)
    cold_dmg = db.Column(db.Integer(), nullable=False, default=0)
    shock_dmg = db.Column(db.Integer(), nullable=False, default=0)
    poison_dmg = db.Column(db.Integer(), nullable=False, default=0)
    absorb_life = db.Column(db.Integer(), nullable=False, default=0)
    health = db.Column(db.Integer(), nullable=False, default=0)
    magicka = db.Column(db.Integer(), nullable=False, default=0)
    fatigue = db.Column(db.Integer(), nullable=False, default=0)
    spell_absorption = db.Column(db.Integer(), nullable=False, default=0)
    water_walking = db.Column(db.Boolean(), nullable=False, default=False)
    detect_life = db.Column(db.Integer(), nullable=False, default=0)
    
class Character(db.Model):
    __tablename__= 'character'
    id = db.Column(db.Integer, nullable=False, unique=True, primary_key=True)
    name = db.Column(db.String(), unique=True, nullable=False)
    race = db.Column(db.String(), nullable=False, default='Altmer')
    gender = db.Column(db.String(), nullable=False, default='Male')
    class_ = db.Column(db.String(), nullable=False, default='Acrobat')
    birthsign = db.Column(db.String(), nullable=False, default='-')
    helmet = db.Column(db.String(), nullable=False, default="-")
    gauntlet = db.Column(db.String(), nullable=False, default="-")
    cuirass = db.Column(db.String(), nullable=False, default="-")
    greaves = db.Column(db.String(), nullable=False, default="-")
    boot = db.Column(db.String(), nullable=False, default="-")
    offhand = db.Column(db.String(), nullable=False, default="-")
    mainhand = db.Column(db.String(), nullable=False, default="-")
    ring1 = db.Column(db.String(), nullable=False, default="-")
    ring2 = db.Column(db.String(), nullable=False, default="-")
    necklace = db.Column(db.String(), nullable=False, default="-")
    damage = db.Column(db.Integer(), nullable=False, default=0)
    rating = db.Column(db.Integer(), nullable=False, default=0)
    strength = db.Column(db.Integer(), nullable=False, default=0)
    endurance = db.Column(db.Integer(), nullable=False, default=0)
    agility = db.Column(db.Integer(), nullable=False, default=0)
    speed = db.Column(db.Integer(), nullable=False, default=0)
    willpower = db.Column(db.Integer(), nullable=False, default=0)
    intelligence = db.Column(db.Integer(), nullable=False, default=0)
    personality = db.Column(db.Integer(), nullable=False, default=0)
    luck = db.Column(db.Integer(), nullable=False, default=0)
    blade = db.Column(db.Integer(), nullable=False, default=0)
    blunt = db.Column(db.Integer(), nullable=False, default=0)
    hand_to_hand = db.Column(db.Integer(), nullable=False, default=0)
    armorer = db.Column(db.Integer(), nullable=False, default=0)
    block = db.Column(db.Integer(), nullable=False, default=0)
    heavy_armor = db.Column(db.Integer(), nullable=False, default=0)
    athletics = db.Column(db.Integer(), nullable=False, default=0)
    acrobatics = db.Column(db.Integer(), nullable=False, default=0)
    light_armor = db.Column(db.Integer(), nullable=False, default=0)
    security = db.Column(db.Integer(), nullable=False, default=0)
    sneak = db.Column(db.Integer(), nullable=False, default=0)
    marksman = db.Column(db.Integer(), nullable=False, default=0)
    mercantile = db.Column(db.Integer(), nullable=False, default=0)
    speechcraft = db.Column(db.Integer(), nullable=False, default=0)
    illusion = db.Column(db.Integer(), nullable=False, default=0)
    alchemy = db.Column(db.Integer(), nullable=False, default=0)
    conjuration = db.Column(db.Integer(), nullable=False, default=0)
    mysticism = db.Column(db.Integer(), nullable=False, default=0)
    alteration = db.Column(db.Integer(), nullable=False, default=0)
    destruction = db.Column(db.Integer(), nullable=False, default=0)
    restoration = db.Column(db.Integer(), nullable=False, default=0)
    fire_res = db.Column(db.Integer(), nullable=False, default=0)
    cold_res = db.Column(db.Integer(), nullable=False, default=0)
    shock_res = db.Column(db.Integer(), nullable=False, default=0)
    magic_res = db.Column(db.Integer(), nullable=False, default=0)
    poison_res = db.Column(db.Integer(), nullable=False, default=0)
    disease_res = db.Column(db.Integer(), nullable=False, default=0)
    paralysis_res = db.Column(db.Integer(), nullable=False, default=0)
    normal_weapon_res = db.Column(db.Integer(), nullable=False, default=0)
    fire_weak = db.Column(db.Integer(), nullable=False, default=0)
    cold_weak = db.Column(db.Integer(), nullable=False, default=0)
    shock_weak = db.Column(db.Integer(), nullable=False, default=0)
    poison_weak = db.Column(db.Integer(), nullable=False, default=0)
    reflect_dmg = db.Column(db.Integer(), nullable=False, default=0)
    reflect_spell = db.Column(db.Integer(), nullable=False, default=0)
    fire_dmg = db.Column(db.Integer(), nullable=False, default=0)
    cold_dmg = db.Column(db.Integer(), nullable=False, default=0)
    shock_dmg = db.Column(db.Integer(), nullable=False, default=0)
    poison_dmg = db.Column(db.Integer(), nullable=False, default=0)
    absorb_life = db.Column(db.Integer(), nullable=False, default=0)
    health = db.Column(db.Integer(), nullable=False, default=0)
    magicka = db.Column(db.Integer(), nullable=False, default=0)
    fatigue = db.Column(db.Integer(), nullable=False, default=0)
    spell_absorption = db.Column(db.Integer(), nullable=False, default=0)
    water_walking = db.Column(db.Boolean(), nullable=False, default=False)
    detect_life = db.Column(db.Integer(), nullable=False, default=0)